name: Matrix Output JSON Demo

on: workflow_dispatch

jobs:
  matrix_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
    steps:
      - name: Store matrix output in a file
        run: |
          echo '{"node": "${{ matrix.node }}"}' >> output.json

      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: matrix_outputs_${{ matrix.node }}
          path: output.json

  collect_outputs:
    runs-on: ubuntu-latest
    needs: matrix_job
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts  # This downloads all artifacts into the "artifacts" directory

      - name: List downloaded files
        run: ls -R artifacts

      - name: Read and process outputs
        run: |
          for file in artifacts/**/output.json; do
            echo "Processing: $file"
            cat "$file" | jq .
          done