name: S10 Label Issues (Permission Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    permissions:
      issues: read
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        if: contains(github.event.issue.title, 'bug')
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          echo "Issue title: $ISSUE_TITLE"
          curl -X POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'content-Type: application/json' \
          -d '{
              "labels": ["bug"]
            }' \
          --fail