name: S7 Matrix Demo
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/s7-controlling-workflow-and-job-execution-88-matrix-demo.yml'
      - 's7-controlling-workflow-and-job-execution-88/**'
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [ 12, 14, 16 ]
        operating-system: [ ubuntu-latest, windows-latest ]
#        dump-array: [ 1,2,3 ]
        include:
          - node-version: latest
            operating-system: macos-latest
        exclude:
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log NodeJS version
        run: node --version