name: Deployment
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/s9-custom-action-114-deploy.yml'
      - 's9-custom-action-114/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load and cache dependencies
        id: cache
        uses: ./.github/actions/cache-deps
        with:
          caching: 'false'
      - name: Lint code
        working-directory: s9-custom-action-114
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load and cache dependencies
        id: cache
        uses: ./.github/actions/cache-deps
      - name: Test code
        id: run-tests
        working-directory: s9-custom-action-114
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: s9-custom-action-114/test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load and cache dependencies
        id: cache
        uses: ./.github/actions/cache-deps
      - name: Build website
        working-directory: s9-custom-action-114
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: s9-custom-action-114/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        run: echo "Deploying..."